imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@TicketBundle/Resources/config/services.yml" }
    - { resource: "@userBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: userBundle\Entity\User
    from_email:
        address: noreply@example.com
        sender_name: Ticketing App

hackzilla_ticket:
    user_class:            userBundle\Entity\User
    ticket_class:           Hackzilla\Bundle\TicketBundle\Entity\TicketWithAttachment
    message_class:          Hackzilla\Bundle\TicketBundle\Entity\TicketMessageWithAttachment
    features:
        attachment:         true
    templates:
        index: 'TicketBundle:Ticket:index.html.twig'
        new: 'TicketBundle:Ticket:new.html.twig'
        prototype: 'TicketBundle:Ticket:prototype.html.twig'
        show: 'TicketBundle:Ticket:show.html.twig'
        show_attachment: 'TicketBundle:Ticket:show_attachment.html.twig'



vich_uploader:
    db_driver: orm
    mappings:
            ticket_message_attachment:
                uri_prefix:         /attachment
                upload_destination: '%kernel.root_dir%/../var/uploads/attachment/'